"""HZO1T1C full read/restore/load service withexplicitconservativeobservationpolicy."""
import math
from model import hardware,lifecycle

def prepare_components(resolved):
 p=resolved['resolved_parameters'];h=hardware(p)
 front={'kind':'polarization','front_end':'case_charge_ports','point_eligibility':'component_only','identity':resolved['input']['implementation_id']+' sourceQ/HVaccess ports','source_ids':['FERAM-03','QMODEL','HV','NATIVE'],'applicability':'NativeSA/hold/LVdecoderonly;casepolarizationQandactualHVaccess,notnvCaporordinaryDRAM','parameters':{'technology_nm':p['technology_nm'],'temperature_K':p['temperature_K'],'rows':p['rows'],'read_columns':p['cols'],'clock_Hz':p['clock_Hz'],'sense_target_V':p['sense_threshold_V'],'sense_pitch_m':p['sense_pitch_m'],'destructive_domain_bits':p['cols'],'restore_lanes':p['restore_lanes'],'BL_wire_extra_cap_F':p['BL_wire_extra_cap_F'],'HV_access_drain_cap_F_each':h['access_C_each_F'],'HV_access_R_ohm':h['access_R_read_bound_ohm'],'LV_decoder_output_load_F':h['LV_decoder_load_F'],'WL_high_voltage_V':p['HV_WL_voltage_V']}}
 digital={'identity':resolved['input']['implementation_id']+' realbinarylocaloperators','point_eligibility':'component_only','parameters':{'technology_nm':p['technology_nm'],'temperature_K':p['temperature_K'],'logical_K':p['rows'],'logical_N':resolved['input']['logical']['N'],'mac_lanes':p['mac_lanes'],'accumulator_bits':p['accumulator_bits'],'weight_hold_rows':1,'weight_hold_outputs':resolved['input']['logical']['N'],'weight_capture_bits':p['cols'],'input_port_bits':p['input_port_bits'],'resident_port_bits':p['resident_port_bits'],'program_lanes':p['external_write_lanes'],'clock_Hz':p['clock_Hz'],'operand_route_cap_F':p['operand_route_cap_F'],'program_control_cap_F':p['program_control_cap_F']}}
 return {'frontend':{'kind':'polarization','request':front},'digital':{'kind':'digital','request':digital}}

def stage(id,t,count,kind,source,resources,includes,excludes):
 s={'id':id,'duration_s':t,'count':int(count),'source_class':kind,'source_ids':source,'resources':resources,'includes':includes,'excludes':excludes}
 if kind=='native_circuit':s.update(native_return_unit='seconds',included_internal_clock_phases='NativeSA includesone1/fenable/outputphase; explicitcaptureusesonefulllegalclock')
 return s

def evaluate(resolved,native):
 p=resolved['resolved_parameters'];f=native['frontend'];d=native['digital'];h=hardware(p,f['actual_BL_total_cap_F']);K=p['rows'];N=resolved['input']['logical']['N'];P=1/p['clock_Hz'];q=p['control_quantum_s'];area=p['FE_area_um2']
 lo,hi=h['states'];ref=h['reference_V'];margin=min(ref-lo['BL_V'],hi['BL_V']-ref)
 control_raw=f['native_LV_decoder_s']+h['WL_loaded_LS_s']+h['WL_loaded_buffer_bound_s'];control=math.ceil(control_raw/q)*q
 precharge=math.ceil((control_raw+h['read_ground_precharge_RC_s'])/q)*q
 # Original100nsisafullobservationcondition. Thisnewpolicy deliberatelywaits
 # ANOTHER100nsafternewactualbiassettles;notamaterialtimeconstant/replay.
 read_bias_settle=control+h['PL_rise_bound_s']
 fullwrite=max(p['full_write_source_s'],h['fullwrite_port_floor_s'])
 clear=max(P,math.ceil(d['state_clear_s']/P)*P)
 hold=max(P,f['native_state_capture_s'],d['weight_hold_capture_s'])
 life=lifecycle(K,p['cols']);bad=lifecycle(K,p['cols'],True)
 checks=[]
 def ck(id,ok,evidence):checks.append({'id':id,'passed':bool(ok),'critical':True,'evidence':evidence})
 ck('real_HZO_identity',f['case_charge_ports']==1 and f['restore_required']==1,'Caseownsremanentpolarizationpaths;nativeaccessisatmostdiagnosticandnotusedat5V')
 ck('charge_conservation',max(abs(x['charge_residual_C']) for x in h['states'])<1e-26,{'branches':h['states'],'CBL_F':h['BL_C_F']})
 ck('sense_margin_and_range',margin>=p['sense_threshold_V']+p['sense_error_V'] and 0<lo['BL_V']<hi['BL_V']<f['native_vdd_V'],{'low_V':lo['BL_V'],'high_V':hi['BL_V'],'reference_V':ref,'minimum_margin_V':margin,'required_V':p['sense_threshold_V']+p['sense_error_V']})
 ck('unselected_PL_hold',h['unselected_FE_voltage_upper_V']<.5,{'unselected_FE_upper_V':h['unselected_FE_voltage_upper_V'],'guard_V':.5,'source':'Wellbelowrough1VcoerciveregioninFig2;fixedfinite-operationqualification,notretentiondistribution','unselected_PL_cap_F':h['unselected_PL_load_F']})
 ck('HVdrive_budget',h['write_peak_source_A']<=p['write_supply_limit_A'] and control_raw<P,{'peak_A':h['write_peak_source_A'],'local_limit_A':p['write_supply_limit_A'],'fullwrite_abs_Q_C':h['fullwrite_abs_charge_C'],'port_floor_s':h['fullwrite_port_floor_s'],'selected_fullwrite_s':fullwrite,'prearm_clock_s':P,'actualcontrol_s':control_raw})
 ck('HV_read_isolation',h['read_park_feedthrough_bound_V']<f['native_vdd_V'],{'worst_full_drain_coupling_V':h['read_park_feedthrough_bound_V'],'native_rail_V':f['native_vdd_V'],'scope':'HVBL/readisolationOFFandactiveLVparkduring2.5Vwrite;unparkonlyaftercompleteenginequiescentreturn'})
 ck('same_source_CBL_scale',240e-15<h['BL_C_F']<260e-15,{'actual_total_F':h['BL_C_F'],'source250fF':'NewK32HVgeometryplusexplicitwire/passiveC,sourcecalibrationloadmatchedwithin1%;not40nmscalingcorner'})
 ck('all_destructive_bits_restored',life['preserved'] and life['restored_bits']==K*p['cols'] and f['actual_state_hold_bits']>=p['cols'] and p['restore_lanes']==p['cols'],{'success':life,'injected_restore_failure':bad,'native_restore_batches':f['restore_batches']})
 ck('failure_zero_payload',bad['completed_payload_Byte']==0,'Everyactivated128bitdomainrestoredfromactualhold;failureinvalidateswholelogicalservice')
 ck('native_digital_clock',d['digital_clock_budget_satisfied']==1,{'period_s':P,'required_s':d['digital_halfcycle_min_period_s']})
 ck('complete_write_not_perpolarity',14e-9<=p['full_write_source_s']<=50e-9,{'source_full_s':p['full_write_source_s'],'physical_port_floor_s':h['fullwrite_port_floor_s'],'charged_once_per128bitrow':True})
 nativeids=['NATIVE'];hv=['HV','NATIVE','POLICY'];FE=['FERAM-03','QMODEL','HV','POLICY'];updates=K*(N//p['mac_lanes'])*8
 stream=[stage('input_admission',P,math.ceil(K*8/p['input_port_bits']),'native_circuit',nativeids,'256bitinputhold/128bitlocalport','All32logicalinputBytesonce','Nooffmacrotransport'),stage('stream_clear',clear,1,'native_circuit',nativeids,'Actualresult/statusclear','Removeoldrequeststate','NotresetFEbits'),stage('input_row_select',P,K,'native_circuit',nativeids,'Nativeinputrow/bytehold','Oneinputbyteperrow','Notparallelinputports'),stage('HV_BL_precharge',precharge,K,'adapter',hv,'128HVgroundprechargers/rowinhibit/refBL','AllWLoff,BL/PL0first,address/controlstable;readstatepreservedatquiescentFEbias','Nooldprechargeaccessbudget'),stage('HV_select_and_plate_settle',read_bias_settle,K,'adapter',FE,'ActualHVaccess/gate+globalPLsource/128refs','TurnselectedWLonlyonthenapply2.5Vplate,includingactualdata/ref/unselectedplatecharge','No100nsdwellalreadyinside'),stage('extra_quasistatic_read_dwell',p['read_dwell_s'],K,'service_policy',['FERAM-03','POLICY'],'ActualbiasedFE/BLnetwork','Newconservative100nswaitAFTERstablebias,basedonsource100nsobservabilitydomain','NotmaterialconstantorclaimedNeuroSimlatency;notold8/20/50nsreadslot'),stage('native_voltage_sense',f['native_voltage_sense_s'],K,'native_circuit',nativeids,'128nativevoltageSA','Latchafterqualifiedchargepoint;native1/foutput/enablephaseincludedonce','No200nscontinuedpolarization-integrationassumption'),stage('allbit_state_weight_capture',hold,K,'native_circuit',nativeids,'128physicalreadhold+128digitalrowhold','Bothholdsreceivedsame128binaryvalues;allactivebitsretainedbeforerestore','Nofullmatrixshadow'),stage('restore_port_prearm',P,K,'adapter',hv,'128truewrite/restorepaths+sourceholdselector','Oneexplicitextraarmingclock/isolation/targetsourcechoicebeforecompletewrite;actualcontrolbudgetfits','Notmaterialpulseorsecondrestorationport'),stage('complete_internal_restore',fullwrite,K,'external_primitive',['FERAM-03','HV'],'Same128HVwritepaths/globalPL','Onefullsource-qualifiedwritecycletooriginal128bitsfromunqualifiedpostreadstates;includesallinternalpolarities/recovery','No2x14ns andrestorepayloadzero'),stage('signed_bitserial_MAC',P,updates,'native_circuit',nativeids,'8native25bitlanes/16resultregisters','8inputbitsx2outputgroupsusingheldcompleteweightrow','Nottruth-correctedanalogoutput'),stage('result_ready',P,1,'service_policy',['POLICY'],'Countedstatus','Publishalreadyheld16outputs','Noextrabytes')]
 resident=[stage('resident_state_clear',clear,1,'native_circuit',nativeids,'Actualstatus/retryclear','Initialcontrolstateclear','NotfreeFEerase'),stage('target_admission',P,K,'native_circuit',nativeids,'128bitrowtarget/localport','All512logicalweightBytesreceivedrowbyrow','Noentirematrixpreload'),stage('external_write_prearm',P,K,'adapter',hv,'Same128physicalHVengines/rowsel/targetmux','Extraarmingclockafterrowtarget;allHVdomainsstablewithquiescentcells','Not14nsinternalphasechargedtwice'),stage('complete_external_row_write',fullwrite,K,'external_primitive',['FERAM-03','HV'],'128physicalwritepaths/sharedwithrestore','Onecompletebipolar-capablewriterowservicefromarbitraryoldstate;includesnativewaveform/recovery','Noerasecreditorperpolarity14nsdoubling'),stage('matrix_ready',P,1,'service_policy',['POLICY'],'Existingstatus','Publishonlyafterall32fullrowsready','Noadditionalpayload')]
 # Integercodingcheckisofflineonly;arraycontentsnotrepairedusingtruth.
 xs=[127 if i%2 else -128 for i in range(K)];w=[[((r*13+c*7)%256)-128 for c in range(N)] for r in range(K)];got=[0]*N
 for r in range(K):
  for b in range(8):
   bit=(xs[r]&255)>>b&1
   for c in range(N):got[c]+=bit*(w[r][c]<<b)*(-1 if b==7 else 1)
 truth=[sum(xs[r]*w[r][c] for r in range(K)) for c in range(N)];ck('signed_local_mapping',got==truth and max(map(abs,got))<1<<24,{'outputs':got})
 resources={'data_FE_capacitors':K*p['cols'],'HV_access_3um_FETs':K*p['cols'],'FE_area_um2_each':area,'physical_shape':[K,p['cols']],'reference_capacitors':p['cols'],'reference_C_each_F':p['reference_cap_F'],'matched_reference_BL_C_each_F':h['BL_C_F'],'SAs':p['cols'],'destructive_domain_bits':p['cols'],'native_read_hold_bits':int(f['actual_state_hold_bits']),'digital_weight_hold_bits':int(d['weight_hold_bits']),'actual_restore_lanes':p['restore_lanes'],'actual_external_write_lanes':p['external_write_lanes'],'data_source_restore_write_mux_bits':p['cols'],'HV_read_isolation_and_park_pairs':p['cols'],'HV_precharge_and_return_FETs':2*p['cols'],'HV_BL_P7_drivers':p['cols']*p['BL_driver_P7_each'],'HV_PL_P7_drivers':p['PL_driver_P7'],'HV_PL_N20_drivers':p['PL_driver_N20'],'HV_levelshift_channels':K+p['cols']+2,'input_hold_bits':int(d['input_hold_bits']),'target_hold_bits':int(d['target_hold_bits']),'output_hold_bits':int(d['signed_output_hold_bits']),'full_matrix_shadow_bits':0,'local2p5V_supply_limit_A':p['write_supply_limit_A'],'BL_wire_extra_C_F':p['BL_wire_extra_cap_F'],'actual_total_BL_C_F':h['BL_C_F'],'unselected_plate_load_F':h['unselected_PL_load_F'],'native_area_m2_partial':f['native_periphery_area_m2']+d['native_digital_area_m2'],'area_qualification':'HV/passivegeometrieslisted,notfullfoundrylayoutorequalareacomparison'}
 conditions=['HZO1T1Cremanentpolarization/destructivereadmaintained;twobranchQispathdependentcharge,notprogrammablenvCap.','100nsextradwellstartsAFTERnewstablebias;itisaconservativepolicybasedonsource100nsmeasurementdomain,notreplayedcompleteaccessornativeprediction.','14nsisonecompletewriteoperation;20/50nsarechosenfull-cyclepoliciesinsourceshmooPASSregion. ActualHVcharge/RCportfloorisappliedwithoutinventingmaterialsubpulses.','Sourcecompletewrite/restore waveform mustremainapplicabletoactual1um2/2.5V/~250fFworkingcellsand128parallelrateddrivers;notnewmacroyieldorsiliconsignoff.','Native1.3VonlydrivesLVlevel-shifterinputsandreadsisolatedlowBLsignals;allmemoryaccess/BL/PLprogramdomainsareHV.','GlobalPLunselectedcellsfloatbehindOFFHVaccess;modeledseriescaploadeverycellandfiniteunselectedfieldguardincluded;longtermfatigue/minor-loopdisturbnotpredicted.','Readlatchesall128bitsthenmarksphysicalstatesunqualifieduntilfullrestore;nooutput-onlyrestorationorfree4096laneport.','SA50mV+50mVerrorbudgetandnominalQbranchesaremodelqualifications;100nsarea crosscheckischargevalidation,notfastkinetics/ENOB.','ConservativeHVblocks/currentbudgetaremodel-levelservices;completecontrolSTA/fastFEkineticsandfullPDNnotclaimed.']
 return {'status':'conditional' if all(c['passed'] for c in checks) else 'infeasible','qualification':'ConditionalHZO1T1Ccharge/nativeperiphery/full128bitrestoremodelwithconservativereaddwell','conditions':conditions,'program_outcome':'success' if life['preserved'] else 'failed','scheduling':'serial_nonoverlap','physical_checks':checks,'resources':resources,'stream_stages':stream,'resident_stages':resident,'diagnostics':{'hardware_charge':h,'control_raw_s':control_raw,'control_guard_s':control,'precharge_block_s':precharge,'read_bias_settle_s':read_bias_settle,'extra_dwell_s':p['read_dwell_s'],'source_full_write_s':p['full_write_source_s'],'complete_write_service_s':fullwrite,'state_lifecycle':life,'restore_failure':bad,'MAC_updates':updates,'read_restore_batches':K,'external_write_batches':K,'phase_semantics':'Readcharge+nativeSA/capture;physicalstateunqualified;full128bitrestore;digitalusesheldrow. NativeSA1/fcountedonce,14nsneverperpolarity.'}}
