#!/usr/bin/env python3
"""One load, U served vectors: exact operator-level II(a), no tile parameters.

Default verifies artifacts; --emit writes current II(a) data/fragment/preview.
"""
import argparse
import csv
from fractions import Fraction as F
import io
import json
from pathlib import Path
import sys
sys.dont_write_bytecode=True
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT.parent / "scripts"))
from format_results import ri_decimal, count_label


def count(U,N,K,b_x=1,b_w=1):
    if any(type(v) is not int or v<=0 for v in [N,K]):raise ValueError('positive integer N,K required')
    if U!='infinity' and (type(U) is not int or U<=0):raise ValueError('positive integer U or symbolic infinity required')
    bx,bw=F(str(b_x)),F(str(b_w))
    if min(bx,bw)<=0:raise ValueError('positive byte widths required')
    qr=N*K*bw
    if U=='infinity':return dict(Q_S='infinity',Q_R=qr,RI='infinity',resident_capacity_bytes=qr)
    qs=U*K*bx
    return dict(Q_S=qs,Q_R=qr,RI=qs/qr,resident_capacity_bytes=qr)


def encode(x):
    if isinstance(x,F):return x.numerator if x.denominator==1 else dict(numerator=x.numerator,denominator=x.denominator)
    if isinstance(x,dict):return {k:encode(v) for k,v in x.items()}
    if isinstance(x,(tuple,list)):return [encode(v) for v in x]
    return x


def tex_ratio(x):
    return ri_decimal(x, tex=True)


def make():
    cfg=json.loads((ROOT/'data/config.json').read_text())
    assert cfg['reference_id']=='OPERATOR-RESIDENCY-v2' and cfg['boundary']=='operator'
    assert not cfg['hardware_parameters'] and cfg['element_bytes']==dict(input=1,weight=1)
    assert cfg['complete_weight_loads']==1
    cases=[]
    for N,K in cfg['matrix_cases_N_K']:
        for U in cfg['U_values']:
            finite=U!='infinity'
            cases.append(dict(case_id=f'N{N}/K{K}/U{U}',kind='finite' if finite else 'limit',
                U=U,N=N,K=K,complete_weight_loads=1,input_shape=[U,K] if finite else None,
                weight_shape=[N,K],output_shape=[U,N] if finite else None,result=count(U,N,K)))
    return cfg,dict(schema_version='2.0',reference_id=cfg['reference_id'],boundary='operator',
        Q_units='Byte',RI_encoding='integer or exact numerator/denominator; infinity is a symbolic limit',
        formulas=cfg['formulas'],element_bytes=cfg['element_bytes'],matrix_cases_N_K=cfg['matrix_cases_N_K'],
        U_values=cfg['U_values'],table_cell_count=35,finite_cases=30,limit_cells=5,
        limit_interpretation=cfg['limit_interpretation'],cases=cases)


def artifacts():
    cfg,data=make()
    headers=[(r'$U\to\infty$' if v=='infinity' else '$U='+count_label(v,True)+'$') for v in cfg['U_values']]
    lines=[r'% Generated by Python from exact Fraction values; rounded display only.',
        r'\begin{table}[htbp]',r'\centering\small',
        r'\caption{五种逻辑权重矩阵在不同复用次数下的 RI}',r'\label{tab:taskIIa-residency}',
        r'\ResultTableSetup',r'\begin{tabularx}{\linewidth}{@{}p{0.22\linewidth}*{7}{>{\centering\arraybackslash}X}@{}}',
        r'\toprule',r'权重形状 $N\times K$ & '+' & '.join(headers)+r'\\',r'\midrule']
    md=['# Table II(a)：一次装载与复用次数 U','',
        '复用次数 U（reuse count）为一次完整权重装载后累计服务的向量数，包含首次使用，可跨多个 batch 或请求。输入和权重均为 1 Byte/element，RI=U/N。','',
        '| 权重形状 N×K | '+' | '.join('U→∞' if v=='infinity' else 'U='+count_label(v) for v in cfg['U_values'])+' |',
        '|---|'+'---:|'*len(cfg['U_values'])]
    for N,K in cfg['matrix_cases_N_K']:
        values=[c['result']['RI'] for c in data['cases'] if (c['N'],c['K'])==(N,K)]
        lines.append('$'+count_label(N,True)+r'\times'+count_label(K,True)+'$ & '+' & '.join('$'+tex_ratio(v)+'$' for v in values)+r'\\')
        md.append(f'| {count_label(N)}×{count_label(K)} | '+' | '.join(ri_decimal(v) for v in values)+' |')
    lines += [r'\bottomrule',r'\end{tabularx}',r'\par\smallskip',r'\begin{minipage}{\linewidth}\footnotesize',
        r'$1\mathrm{K}=1024$，$1\mathrm{M}=1024^2$；直立 K/M 是数量后缀，斜体 $K$ 是矩阵输入维度。'
        r'RI 至少为 1 时保留一位小数，小于 1 时保留三位有效数字；精确值保存在机器数据中。'
        r'末列为一次装载的无界复用极限，写入量仍为有限的 $NK$ Byte。',
        r'\end{minipage}',r'\end{table}','']
    md += ['', '数量后缀 1K=1024、1M=1024²；RI≥1 保留一位小数，RI<1 保留三位有效数字。小数仅用于显示，精确分数保留在 [JSON](data/results.json) / [CSV](data/results.csv)。',
        '', 'U=1 时 RI=1/N；U→∞ 时输入量无界增长，单次写入量 NK 不变。相同 N 的矩阵具有相同 RI；K 同时缩放输入与写入量，故在比例中抵消。','']
    out=io.StringIO();w=csv.writer(out,lineterminator='\n')
    w.writerow(['case_id','kind','N','K','U','complete_weight_loads','boundary','Q_S_Byte','Q_R_Byte','RI_exact','resident_capacity_Byte'])
    for c in data['cases']:
        w.writerow([c[k] for k in ['case_id','kind','N','K','U','complete_weight_loads']]+['operator']+
            [str(c['result'][k]) for k in ['Q_S','Q_R','RI','resident_capacity_bytes']])
    return {'data/results.json':json.dumps(encode(data),ensure_ascii=False,indent=2)+'\n',
        'data/results.csv':out.getvalue(),'tex/table_fragment.tex':'\n'.join(lines),'PREVIEW.zh.md':'\n'.join(md)}


def main():
    p=argparse.ArgumentParser();p.add_argument('--emit',action='store_true');args=p.parse_args()
    for name,content in artifacts().items():
        path=ROOT/name
        if args.emit:path.write_text(content)
        else:assert path.read_text()==content,'stale current II(a) artifact: '+name
    print('PASS: II(a) RI=U/N; 5 matrix shapes x 7 U levels; 30 finite cases + 5 symbolic limits')


if __name__=='__main__':main()
