#!/usr/bin/env python3
"""Generate exact Table II(a) JSON and the reusable English TeX table fragment."""
from pathlib import Path
import argparse
import json
from fractions import Fraction
from decimal import Decimal
import counting as c

ROOT=Path(__file__).resolve().parents[2]

def tex_bytes(n):
    for divisor,label in [(1048576,'MiB'),(1024,'KiB')]:
        if n and n%divisor==0:return str(n//divisor)+r'\,\mathrm{'+label+'}'
    return str(n)+r'\,\mathrm{B}'

def tex_cell(d):
    ratio=r'\infty' if d['RI']=='infinity' else str(d['RI'].numerator)+'/'+str(d['RI'].denominator)
    return (r'\begin{tabular}[t]{@{}c@{}}$Q_S='+tex_bytes(d['Q_S'].numerator)+r'$\\'
            r'$Q_R='+tex_bytes(d['Q_R'].numerator)+r'$\\$\mathrm{RI}='+ratio+r'$\end{tabular}')

def main(emit):
    plan=json.loads((ROOT/'data/study_plan.json').read_text())
    rows=[]
    for rid,title,loads in [('weight_static','Weight-static',0),('per_use_reloaded','Per-use reloaded',1)]:
        cells=[]
        for n,k in plan['table_IIa']['columns_N_K']:
            result=c.matvec(n,k,loads=loads)
            cells.append({'N':n,'K':k,'operator':result['operator'],'ports':result['ports'],'tile_layout':result['tile_layout']})
        rows.append({'id':rid,'label':title,'window_input_vectors':1,'window_complete_weight_loads':loads,'cells':cells})
    data={'schema_version':'1.0','reference_id':'WS128-INT8-semantic-banks-v1','status':'Step 2完成，待审阅',
          'primary_boundary':'ports','contrast_boundary':'operator','Q_units':'Byte','element_bytes':{'input':1,'weight':1},
          'tile_shape_N_K':[128,128],'RI_encoding':'exact rational {numerator,denominator}; string infinity for static positive-work branch',
          'table_primary_dynamic_RI_exact_decimal':'0.0078125','rows':rows}
    lines=[r'% Generated by shared/scripts/generate_IIa.py; do not hand-edit values.',
           r'% Requires booktabs, tabularx, array. Standalone numbering is set by table_IIa.tex.',
           r'\begin{table*}[htbp]',r'\centering',r'\caption{Resident--streaming demand at two residency endpoints.}',r'\label{tab:taskIIa-residency}',
           r'\small',r'\setlength{\tabcolsep}{3pt}',r'\renewcommand{\arraystretch}{1.2}',
           r'\begin{tabularx}{\textwidth}{@{}l*{5}{>{\centering\arraybackslash}X}@{}}',r'\toprule',
           'Residency & '+' & '.join(r'$'+str(n)+r'\!\times\!'+str(k)+'$' for n,k in plan['table_IIa']['columns_N_K'])+r' \\',r'\midrule']
    for row in rows:
        label=r'\shortstack[l]{Per-use\\reloaded}' if row['id']=='per_use_reloaded' else row['label']
        lines.append(label+' & '+' & '.join(tex_cell(x['ports']) for x in row['cells'])+r' \\[5pt]')
    lines += [r'\bottomrule',r'\end{tabularx}',r'\par\smallskip',r'\begin{minipage}{\textwidth}\footnotesize',
      r'The primary boundary sums valid logical payload at all $128\times128$ tile input receivers. '
      r'Each column specifies the logical weight shape $N\times K$ (outputs $\times$ inputs), not a new physical macro. '
      r'Each window evaluates one input vector; input and resident elements are one byte (INT8 reference). '
      r'Weight-static assumes preloading before the window; per-use reloaded writes the complete weight matrix once within it. '
      r'$\mathrm{RI}=Q_S/Q_R$, with $\mathrm{RI}=\infty$ for $Q_R=0$. '
      r'Here, all dynamic ratios equal $1/128=0.0078125$. '
      r'$1\,\mathrm{KiB}=1024\,\mathrm{B}$; $1\,\mathrm{MiB}=1048576\,\mathrm{B}$.',
      r'\end{minipage}',r'\end{table*}','']
    def zh_int(n):return f'{int(n):,}'.replace(',',r'\,')
    zh_rows=[]
    for x in rows[1]['cells']:
        ratio=x['operator']['RI']
        zh_rows.append('$('+str(x['N'])+','+str(x['K'])+')$ & '+str(x['ports']['tile_evaluations'])+' & '+zh_int(x['operator']['Q_S'])+' & '+zh_int(x['ports']['Q_S'])+' & '+zh_int(x['ports']['Q_R'])+' & $'+str(ratio.numerator)+'/'+str(ratio.denominator)+r'$ \\')
    artifacts={'table_IIa/data/results.json':json.dumps(c.encode(data),ensure_ascii=False,indent=2)+'\n',
               'table_IIa/tex/table_fragment.tex':'\n'.join(lines),
               'shared/tex/IIa_values.generated.tex':'% Generated exact II(a) contrast values.\n'+r'\begin{tabular}{@{}rrrrrr@{}}\toprule'+'\n'+r'$(N,K)$ & tile/调用数 & $\qso$ (Byte) & $\qsl$ (Byte) & 动态 $\qr$ (Byte) & 动态 $\riop$\\\midrule'+'\n'+'\n'.join(zh_rows)+'\n'+r'\bottomrule\end{tabular}'+'\n'}
    for rel,text in artifacts.items():
        p=ROOT/rel
        if emit:p.write_text(text)
        else:assert p.read_text()==text,'stale generated output: '+rel
    print('Table II(a): 10 cells, both boundaries retained, all values exact; '+('generated' if emit else 'verified'))

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--emit',action='store_true');main(p.parse_args().emit)
