#!/usr/bin/env python3
"""Index evidence and cache exact PDF pages; never download or use OCR.

Only --render requires pdfplumber/pypdfium2 and available local-only PDFs.
Without --render, public metadata and fact notes can be rebuilt offline.
"""
from pathlib import Path
import argparse
import hashlib
import json
import logging

ROOT = Path(__file__).resolve().parents[1]


def read(path):
    return json.loads((ROOT / path).read_text())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--render", action="store_true")
    args = parser.parse_args()
    sources = read("sources/manifest.json")
    evidence = read("data/extractions.json")
    captures = read("sources/capture_plan.json")
    records = read("data/implementations.json")
    plan = {x["source_id"]: x for x in captures}
    index = ["# Source and evidence index", "",
             "Generated by `scripts/prepare_sources.py`. Page numbers below are 1-based PDF pages, unless explicitly identified as printed article pages. Full PDFs, extracted text and page images remain under ignored `sources/local-only/`.", "",
             "[Manifest](manifest.json) records versions, access status and SHA-256. [Access log](access_log.json) records follow-up searches and specific limitations. [Capture plan](capture_plan.json) is the stable page locator even when local-only files are absent.", ""]
    if args.render:
        import pdfplumber
        logging.getLogger("pdfminer").setLevel(logging.ERROR)
    capture_results = []
    notes_dir = ROOT / "sources/notes"
    notes_dir.mkdir(exist_ok=True)
    for s in sources:
        sid = s["source_id"]
        evs = [e for e in evidence if sid in e["source_ids"]]
        linked = [r["record_id"] for r in records if sid in r["source_ids"]]
        index.extend([f"## {sid}", "", f"**{s['title']}** ({s['year']}). {s['venue']}.", "",
                      f"Identity: {s['official_url']}. Access: `{s['access_status']}`; {s['version']}.", "",
                      "Records: " + (", ".join(f"`{r}`" for r in linked) or "Bibliographic follow-up only; no invented hardware record.") + "", ""])
        if s.get("access_note"):
            index.extend([s["access_note"], ""])
        for e in evs:
            index.extend([f"- [{e['evidence_id']}](notes/{e['evidence_id']}.md): {e['location']}"])
            lines = [f"# {e['evidence_id']}", "", "Generated from `data/extractions.json`; edit that JSON to correct facts.", "",
                     f"Sources: {', '.join(e['source_ids'])}", "", f"Location: {e['location']}", "",
                     f"Supports: {e['supports']}", "", f"Does not support: {e['does_not_support']}", "",
                     "Extraction: " + e["extraction_method"] + ". Values are text or explicit figure labels; no continuous-curve digitization is used.", "",
                     "| Key | Original value | Unit | Relation | Result origin | Derivation |",
                     "|---|---:|---|---|---|---|"]
            for k, v in e["values"].items():
                lines.append(f"| `{k}` | {v['value']} | {v['unit']} | {v.get('relation', 'See key and source condition')} | {v['result_origin']} | {v['derivation_kind']} |")
            (notes_dir / f"{e['evidence_id']}.md").write_text("\n".join(lines) + "\n")
        index.append("")
        if sid in plan:
            index.extend(["Cached-page plan: " + "; ".join(f"p.{p['pdf_page']}: {p['purpose']}" for p in plan[sid]["pages"]) + ".", ""])
        if not args.render or not s["local_file"]:
            continue
        p = ROOT / s["local_file"]
        if not p.exists():
            capture_results.append(dict(source_id=sid, status="ignored_local_pdf_absent"))
            continue
        assert p.read_bytes().startswith(b"%PDF")
        assert hashlib.sha256(p.read_bytes()).hexdigest() == s["sha256"]
        out = ROOT / "sources/local-only/evidence_pages" / sid
        out.mkdir(parents=True, exist_ok=True)
        with pdfplumber.open(p) as pdf:
            for c in plan[sid]["pages"]:
                n = c["pdf_page"]
                assert 1 <= n <= len(pdf.pages)
                page = pdf.pages[n - 1]
                png = out / f"p{n:02d}.png"
                txt = out / f"p{n:02d}.txt"
                page.to_image(resolution=170).save(png)
                txt.write_text(page.extract_text() or "")
                capture_results.append(dict(source_id=sid, pdf_page=n, purpose=c["purpose"],
                    source_sha256=s["sha256"], page_count=len(pdf.pages),
                    image_path=png.relative_to(ROOT).as_posix(), text_path=txt.relative_to(ROOT).as_posix(),
                    image_sha256=hashlib.sha256(png.read_bytes()).hexdigest(),
                    method="Exact whole-page PDF rendering at 170 dpi; pdfplumber text; no OCR or curve digitization."))
    (ROOT / "sources/EVIDENCE_INDEX.md").write_text("\n".join(index) + "\n")
    if args.render:
        (ROOT / "sources/page_index.json").write_text(json.dumps(capture_results, ensure_ascii=False, indent=2) + "\n")
    print(f"Indexed {len(sources)} sources, {len(evidence)} evidence groups; rendered {len(capture_results)} page/status records.")


if __name__ == "__main__":
    main()
