"""Conditional native RRAM/FeRAM layout models; no timing or macro PPA.
All lengths are um. Each model returns a complete repeated tile with b=1.
Primitive geometry is generated by an independently built locked NeuroSim adapter.
"""
from __future__ import annotations
import copy, hashlib, json, math

def digest_object(x):
    return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()).hexdigest()

def _variants(inputs):
    variants={}
    for cid,c in inputs['cases'].items():
        variants[cid+':main']=copy.deepcopy(c)
        loose=copy.deepcopy(c)
        # Finite layout condition, NOT an electrical/process corner.
        loose['rules']={k:v*1.2 for k,v in c['rules'].items()}
        variants[cid+':loose_rules_20pct']=loose
        for item in c['single_parameter_checks']:
            alt=copy.deepcopy(c)
            ptr=item['path'].split('.')
            target=alt
            for key in ptr[:-1]:target=target[key]
            target[ptr[-1]]=item['value']
            variants[cid+':'+item['id']]=alt
    return variants

def _mos_query(qid,F,mos,r):
    h=max(mos['W_um']+3.6*F,mos['W_um']+2*r['poly_extension_um']+r['field_poly_gap_um'])
    landing=max(r['metal_width_um'],r['contact_um']+2*r['via_enclosure_um'])
    gap=max(r['gate_contact_gap_um'],(landing+r['metal_gap_um']-mos['L_um']-r['contact_um'])/2)
    return dict(id=qid,F_um=F,W_um=mos['W_um'],L_um=mos['L_um'],H_um=h,
                contact_um=r['contact_um'],gap_um=gap,enclosure_um=r['diff_enclosure_um'],
                nominal_gate_contact_gap_um=r['gate_contact_gap_um'])

def primitive_queries(inputs):
    q=[]
    for vid,c in _variants(inputs).items():
        for mid,mos in c['devices'].items():q.append(_mos_query(vid+':'+mid,c['geometry_scale_um'],mos,c['rules']))
    return q

def _rectangle(name,layer,net,x,y,w,h,kind='allocation'):
    return dict(name=name,layer=layer,net=net,x_um=x,y_um=y,width_um=w,height_um=h,kind=kind)

def _terminal_x(p,dev,r):
    # One true gate, two contacted diffusions. Native NeuroSim slack is
    # distributed symmetrically around the explicit physical strip.
    inset=max(0,(p['adapted_width_um']-p['contact_span_um'])/2)
    gap=p['query']['gap_um']
    source=inset+r['diff_enclosure_um']+r['contact_um']/2
    gate=inset+r['diff_enclosure_um']+r['contact_um']+gap+dev['L_um']/2
    drain=inset+r['diff_enclosure_um']+r['contact_um']+2*gap+dev['L_um']+r['contact_um']/2
    pad=max(r['metal_width_um'],r['contact_um']+2*r['via_enclosure_um'])
    outward=max(0,(r['metal_gap_um']-(drain-source-pad))/2)
    source-=outward;drain+=outward
    if source-pad/2 < -1e-12 or drain+pad/2 > p['adapted_width_um']+1e-12:
        raise ValueError('source/drain pad placement needs a wider MOS allocation')
    return {'source':source,'gate':gate,'drain':drain,'pad_shift_outward_um':outward,
            'same_layer_SD_pad_gap_um':drain-source-pad,
            'actual_source_contact_to_gate_gap_um':gate-dev['L_um']/2-(source+r['contact_um']/2),
            'actual_drain_contact_to_gate_gap_um':drain-r['contact_um']/2-(gate+dev['L_um']/2)}

def _route(net,layer,points,width,ports=None):
    return {'net':net,'layer':layer,'points_um':points,'width_um':width,'boundary_ports':ports or []}

def _rram(c,pr):
    r=c['rules'];F=c['geometry_scale_um'];t1=pr['T1'];t2=pr['T2']
    assert c.get('m',1)==1 and c['devices']['T2'].get('m',1)==1, 'Only source m=1 identity is supported'
    p1=_terminal_x(t1,c['devices']['T1'],r);p2=_terminal_x(t2,c['devices']['T2'],r)
    pad=max(r['metal_width_um'],r['contact_um']+2*r['via_enclosure_um'])
    lane=pad+r['metal_gap_um']
    wcore=max(t1['adapted_width_um'],t2['adapted_width_um'],c['rram_landing_side_um']+2*r['metal_gap_um'],p1['drain']+c['rram_landing_side_um']/2)
    # Main: separate active regions. No unproved source/drain sharing.
    h1=t1['query']['H_um'];h2=t2['query']['H_um']
    # The upper RRAM is contained over T1 if small, and expands its allocation if not.
    h1=max(h1,c['rram_landing_side_um']+2*r['metal_gap_um'])
    width=wcore+2*lane
    height=h1+h2+4*lane
    yground=0.0;ytbl=lane;yt2=2*lane;yx=yt2+h2;yt1=yx+lane;ywl=yt1+h1
    rects=[
       _rectangle('T1 isolated contacted NMOS','FEOL','SL-X/WL',lane,yt1,t1['adapted_width_um'],h1),
       _rectangle('T2 isolated contacted NMOS','FEOL','GND-TBL/X',lane,yt2,t2['adapted_width_um'],h2),
       _rectangle('WL gate-contact channel','M2','WL',0,ywl,width,lane),
       _rectangle('local X gate-landing channel','M1+M2','X',lane,yx,wcore,lane),
       _rectangle('TBL routing channel','M2','TBL',0,ytbl,width,lane),
       _rectangle('GND and body-tie allocation','M1+PwellTap','GND',0,yground,width,lane),
       _rectangle('SL vertical routing gutter','M3','SL',0,0,lane,height),
       _rectangle('BL vertical routing gutter','M3','BL',lane+wcore,0,lane,height),
       _rectangle('RRAM + upper electrode landing','BEOL RRAM','X-BL',lane+p1['drain']-c['rram_landing_side_um']/2,yt1+(h1-c['rram_landing_side_um'])/2,c['rram_landing_side_um'],c['rram_landing_side_um'],'storage_device_assumed_envelope')]
    terminals={
      'T1_SL':[lane+p1['source'],yt1+h1/2], 'T1_X':[lane+p1['drain'],yt1+h1/2],
      'T1_WL':[lane+p1['gate'],ywl+lane/2], 'T2_GND':[lane+p2['source'],yt2+h2/2],
      'T2_TBL':[lane+p2['drain'],yt2+h2/2], 'T2_X_gate':[lane+p2['gate'],yx+lane/2]}
    for name,pt in terminals.items():
        rects.append(_rectangle(name+' landing','contact/via stack',name.split('_',1)[1],pt[0]-pad/2,pt[1]-pad/2,pad,pad,'contact_landing'))
    routes=[
      _route('WL','M2',[[0,terminals['T1_WL'][1]],[width,terminals['T1_WL'][1]]],r['metal_width_um'],['left','right']),
      _route('TBL','M2',[[0,ytbl+lane/2],[width,ytbl+lane/2]],r['metal_width_um'],['left','right']),
      _route('SL','M3',[[lane/2,0],[lane/2,height]],r['metal_width_um'],['bottom','top']),
      _route('BL','M3',[[width-lane/2,0],[width-lane/2,height]],r['metal_width_um'],['bottom','top']),
      _route('GND','M1',[[0,lane/2],[width,lane/2]],r['metal_width_um'],['left','right']),
      _route('SL','M1 to M3 via',[terminals['T1_SL'],[lane/2,terminals['T1_SL'][1]]],r['metal_width_um']),
      _route('X','M1',[terminals['T1_X'],[terminals['T1_X'][0],yx+lane/2],terminals['T2_X_gate']],r['metal_width_um']),
      _route('GND','M1',[terminals['T2_GND'],[terminals['T2_GND'][0],lane/2]],r['metal_width_um']),
      _route('TBL','M1 to M2 via',[terminals['T2_TBL'],[terminals['T2_TBL'][0],ytbl+lane/2]],r['metal_width_um']),
      _route('BL','RRAM top electrode to M3',[terminals['T1_X'],[width-lane/2,terminals['T1_X'][1]]],r['metal_width_um'])]
    return dict(width_um=width,height_um=height,area_xy_um2=width*height,independent_bits=1,
         terminals_um=terminals,routes=routes,terminal_placement={'T1':p1,'T2':p2},
         connectivity_notes=['RRAM bottom electrode is a vertical connection at T1_X; top electrode connects BL on a distinct upper layer.','Local X connects T1 drain/RRAM bottom electrode to T2 gate; it is not another row control.','Contacts occupy explicit landing pads; crossings on different stated layers are insulated. Allocation geometry is not a foundry DRC/LVS result.'],
         transistor_regions={'T1':t1,'T2':t2},rectangles=rects,routing_lane_pitch_um=lane,landing_pad_um=pad,
         diffusion_sharing='none between T1/T2 or adjacent cells; distinct electrical nets retained',
         gate_controls={'T1':'WL','T2':'local X (not a second WL)'},
         tile_boundary='one fully allocated two-island WH-2T1R m=1 cell including local X/SL/BL/WL/TBL/GND, body tie and assumed RRAM landing',
         storage_containment=dict(rram_side_um=c['rram_landing_side_um'],reported_device_size=False,rram_fits_upper_allocation=True),
         upper_lower_area_rule='coordinate bounding envelope; upper RRAM overlaps T1 projection, not added as separate area')

def _feram(c,pr):
    r=c['rules'];mos=pr['access'];dev=c['devices']['access'];cap=c['capacitor']
    pad=max(r['metal_width_um'],r['contact_um']+2*r['via_enclosure_um'])
    lane=pad+r['metal_gap_um']
    active_w=dev['W_um'];
    gate_top=r['gate_contact_to_active_um']+r['contact_um']+2*r['gate_contact_enclosure_um']+r['field_poly_gap_um']/2
    body_bottom=r['active_gap_um']+r['contact_um']+2*r['diff_enclosure_um']+r['active_gap_um']/2
    # No aggregate max(Aaccess,Acap). Construct both layers at explicit coordinates.
    access_h=max(mos['query']['H_um'],active_w+gate_top+body_bottom)
    access_x=lane;access_y=0.0
    source_keepout=r['diff_enclosure_um']+r['contact_um']+r['gate_contact_gap_um']
    cap_w=math.sqrt(cap['active_area_um2']*cap['aspect_ratio'])
    cap_h=math.sqrt(cap['active_area_um2']/cap['aspect_ratio'])
    cap_outer_w=cap_w+2*r['electrode_margin_um']
    cap_outer_h=cap_h+2*r['electrode_margin_um']
    access_terminals=_terminal_x(mos,dev,r)
    cap_x=max(access_x+source_keepout,access_x+access_terminals['source']+pad/2+r['electrode_margin_um'])
    cap_y=body_bottom+max(0,(active_w-cap_outer_h)/2)
    # BL passes vertically in a left lane, above FEOL/CUB. PL and WL use
    # orthogonal upper layers, with local pads included in their landing channels.
    width=max(access_x+mos['adapted_width_um'],cap_x+cap_outer_w)+r['metal_gap_um']/2
    wl_center_y=max(body_bottom+active_w+r['gate_contact_to_active_um']+r['contact_um']/2,
                    cap_y+cap_outer_h+r['electrode_margin_um']+pad/2)
    access_h=max(access_h,wl_center_y+pad/2+r['metal_gap_um']/2)
    gate_top=access_h-body_bottom-active_w
    height=max(access_h,cap_y+cap_outer_h+r['metal_gap_um']/2)
    rects=[
       _rectangle('contacted access NMOS with gate/body landing','FEOL','BL-SN/WL',access_x,access_y,mos['adapted_width_um'],access_h),
       _rectangle('NMOS channel active','FEOL active','BL-SN',access_x+source_keepout,body_bottom,dev['L_um'],active_w,'channel'),
       _rectangle('MFM electrode envelope','CUB above transistor','SN-PL',cap_x,cap_y,cap_outer_w,cap_outer_h),
       _rectangle('MFM active switching area','CUB active','SN-PL',cap_x+r['electrode_margin_um'],cap_y+r['electrode_margin_um'],cap_w,cap_h,'storage_device'),
       _rectangle('BL vertical route and source landing','M1','BL',0,0,lane,height),
       _rectangle('WL top gate landing channel','M3','WL',0,body_bottom+active_w,width,gate_top),
       _rectangle('PL over-cap routing and top contact','M2','PL',0,cap_y+cap_outer_h/2-pad/2,width,pad),
       _rectangle('local body tie allocation','PwellTap+M1','GND',access_x,0,mos['adapted_width_um'],body_bottom)]
    t=_terminal_x(mos,dev,r)
    terminals={'BL_source':[access_x+t['source'],body_bottom+active_w/2],
      'SN_drain_bottom_electrode':[access_x+t['drain'],body_bottom+active_w/2],
      'WL_gate':[access_x+t['gate'],wl_center_y],
      'PL_top_electrode':[cap_x+cap_outer_w/2,cap_y+cap_outer_h/2],
      'body_ground':[access_x+t['source'],r['active_gap_um']/2+(r['contact_um']+2*r['diff_enclosure_um'])/2]}
    for name,pt in terminals.items():
        rects.append(_rectangle(name+' contact landing','contact/via stack',name,pt[0]-pad/2,pt[1]-pad/2,pad,pad,'contact_landing'))
    routes=[
      _route('BL','M1',[[lane/2,0],[lane/2,height]],r['metal_width_um'],['bottom','top']),
      _route('BL','M1',[[lane/2,terminals['BL_source'][1]],terminals['BL_source']],r['metal_width_um']),
      _route('WL','M3',[[0,terminals['WL_gate'][1]],[width,terminals['WL_gate'][1]]],r['metal_width_um'],['left','right']),
      _route('PL','M2',[[0,terminals['PL_top_electrode'][1]],[width,terminals['PL_top_electrode'][1]]],r['metal_width_um'],['left','right']),
      _route('GND','M4',[[0,terminals['body_ground'][1]],[width,terminals['body_ground'][1]]],r['metal_width_um'],['left','right'])]
    return dict(width_um=width,height_um=height,area_xy_um2=width*height,independent_bits=1,
         terminals_um=terminals,routes=routes,terminal_placement={'access':t},
         gate_contact_cap_clearance_um=wl_center_y-pad/2-(cap_y+cap_outer_h),
         source_contact_cap_clearance_um=cap_x-(terminals['BL_source'][0]+pad/2),
         connectivity_notes=['Source BL contact lies left of the capacitor shadow; a horizontal M1 spur connects it to the continuous vertical BL.','Drain SN contact terminates at the lower MFM electrode above the access region; it is not shorted to the PL top contact.','PL M2 and WL M3 extend through both tile boundaries; their local contact stacks are at separate y positions. The body contact reaches a separate continuous M4 ground line.','Contacts and routes are assigned to explicit isolated layers; geometry is a conditional placement allocation, not a foundry DRC/LVS result.'],
         transistor_regions={'access':mos},rectangles=rects,routing_lane_pitch_um=lane,
         capacitor_active_width_um=cap_w,capacitor_active_height_um=cap_h,
         capacitor_outer_width_um=cap_outer_w,capacitor_outer_height_um=cap_outer_h,
         transistor_only_allocated_width_um=mos['adapted_width_um'],transistor_only_allocated_height_um=access_h,
         cap_shape_is_reported=False,diffusion_sharing='no source/drain sharing; per-cell body-tie allocation; same pwell continuous',
         tile_boundary='one conditional 130 nm CUB 1T1C tile including single HV NMOS, source BL access, WL/PL contacts, MFM electrode margins and body tie',
         upper_lower_area_rule='explicit aligned rectangles; electrode footprint overlaps gate/drain region while source BL landing remains outside cap shadow')

def _measure(c,m):
    a=m['area_xy_um2']/m['independent_bits'];m['a_bit_um2']=a;m['density_Mbit_mm2']=1/a
    m['alpha_F2_per_bit']=a/(c['F_mem_nm']/1000)**2;m['F_mem_nm']=c['F_mem_nm']
    return m

def calculate_models(inputs,primitive_record):
    if primitive_record['input_sha256']!=digest_object(inputs):raise ValueError('primitive record was built for different model inputs')
    if primitive_record['upstream_sha']!='8a88abf85844c0e1ba17cc771ea535fff6040456':raise ValueError('NeuroSim SHA mismatch')
    queries=primitive_queries(inputs)
    if primitive_record['query_sha256']!=digest_object(queries):raise ValueError('primitive query mismatch')
    records=primitive_record['primitives'];querymap={q['id']:q for q in queries}
    results={};checks={}
    for vid,c in _variants(inputs).items():
        pr={}
        for mid in c['devices']:
            q=querymap[vid+':'+mid];p=copy.deepcopy(records[q['id']])
            if p['query']!=q:raise ValueError('input W/L/F/contact mismatch: '+q['id'])
            if p['fingers']!=1:raise ValueError('unexpected folding in conditional single-finger tile')
            expected=7.6*q['F_um']
            if not math.isclose(p['native_width_um'],expected,rel_tol=1e-11):raise ValueError('native NMOS branch mismatch')
            if not math.isclose(p['length_correction_um'],q['L_um']-q['F_um'],rel_tol=1e-11):raise ValueError('long gate not propagated')
            if not math.isclose(p['adapted_width_um'],max(p['native_width_um']+p['length_correction_um'],p['contact_span_um']),rel_tol=1e-11):raise ValueError('adapter width mismatch')
            pr[mid]=p
        m=_rram(c,pr) if vid.startswith('05_rram') else _feram(c,pr)
        _measure(c,m);m['condition_id']=vid
        for place in m['terminal_placement'].values():
            if place['same_layer_SD_pad_gap_um'] < c['rules']['metal_gap_um']-1e-10:raise ValueError('S/D landing metal space violated')
            for key in ['actual_source_contact_to_gate_gap_um','actual_drain_contact_to_gate_gap_um']:
                if place[key] < c['rules']['gate_contact_gap_um']-1e-10:raise ValueError('contact-to-gate rule violated')
        if vid.startswith('08_'):
            if m['gate_contact_cap_clearance_um'] < c['rules']['electrode_margin_um']-1e-10:raise ValueError('WL contact crosses capacitor shadow')
            if m['source_contact_cap_clearance_um'] < c['rules']['electrode_margin_um']-1e-10:raise ValueError('BL contact crosses capacitor shadow')
        m['local_rule_checks']={'source_drain_pad_metal_spacing':True,'contact_to_gate_spacing':True,'rectangles_contained':True,'cap_gate_and_BL_contact_shadow_clear':True if vid.startswith('08_') else 'not_CUB'}
        # Geometric containment, cap-area conservation and positive units.
        for z in m['rectangles']:
            if z['width_um']<=0 or z['height_um']<=0:raise ValueError('nonpositive region')
            if z['x_um']<0 or z['y_um']<0 or z['x_um']+z['width_um']>m['width_um']+1e-10 or z['y_um']+z['height_um']>m['height_um']+1e-10:raise ValueError('region outside envelope: '+z['name'])
        if vid.endswith(':main'):results[vid.split(':')[0]]=m
        else:checks[vid]=m
    for key,m in checks.items():
        main=results[key.split(':')[0]];m['relative_area_change']=m['area_xy_um2']/main['area_xy_um2']-1
    return {'schema_version':'conditional-cell-layout-results-1','case_results':results,'sensitivity':checks,
      'model_input_sha256':digest_object(inputs),'primitive_query_sha256':digest_object(queries),
      'scope':'Geometry plus static device-domain plausibility only; no timing, full macro, foundry DRC or original-chip layout reconstruction',
      'normalization_invariance':'F_mem is used only after absolute geometry, independent of geometry_scale_um'}
