#!/usr/bin/env python3
"""Read-only recomputation/contract checks. --emit explicitly refreshes results/TeX."""
import argparse
import hashlib
import importlib.util
import json
import math
import sys
from pathlib import Path
import unittest

sys.dont_write_bytecode = True
BASE = Path(__file__).resolve().parents[1]
SHARED = BASE.parent / 'shared_baseline'
CORPUS = BASE.parents[1]
spec = importlib.util.spec_from_file_location('shared_model', SHARED/'scripts/check_shared.py')
api = importlib.util.module_from_spec(spec)
spec.loader.exec_module(api)
I = json.loads((BASE/'data/inputs.json').read_text())
M = I['mapping']
CFG = {**api.R['dcim'], **I['stream_configuration_overrides']}


def calculate(s, attempts=None):
    v = api.C['propagation']['profile_values'][s['profile']]
    td = v['digital_tick']
    ds, counts = api.dcim_service(CFG, v, s['read_response_ns'])
    front, beats = api.front_ns(M['encoded_load_bits'], td, M['first_data_in_command'])
    physical_writes = M['first_phase_active_MTJs'] + M['second_phase_active_MTJs']
    q = physical_writes*s['write_error_proxy_per_state_command']
    assert 0 <= q < 1
    steps = [dict(count=1, drive_program_ns=s['write_access_slot_ns'], verify_ns=0, recover_ns=M['polarity_switch_ticks']*td),
             dict(count=1, drive_program_ns=s['write_access_slot_ns'], verify_ns=0, recover_ns=0),
             dict(count=M['verify_branch_batches'], drive_program_ns=0, verify_ns=s['read_response_ns'],
                  recover_ns=M['compare_ticks_per_verify_batch']*td)]
    one = api.program_sequence_ns(0, 0, steps)
    finite_attempts = I['retry_model']['main_attempts'] if attempts is None else attempts
    dr = front + finite_attempts*one
    br = M['logical_weights_per_write_group']*api.L['b_R']
    result = api.metrics(api.L['B_S_Byte'], br, ds, dr)
    result.update(profile=s['profile'], baseline_id=api.D['baseline_id'], mode=I['mode'],
                  granularity='one vector / one 8-Byte completed write group',
                  read_response_ns=s['read_response_ns'], write_access_slot_ns=s['write_access_slot_ns'],
                  stream_counts=counts, resident_counts=dict(encoded_data_beats=beats,
                      first_phase_MTJ_commands=M['first_phase_active_MTJs'], second_phase_MTJ_commands=M['second_phase_active_MTJs'],
                      total_MTJ_commands_per_attempt=physical_writes, verify_batches=M['verify_branch_batches'],
                      verified_MTJs_per_attempt=M['verify_branch_batches']*M['verify_single_ended_sense_lanes'],
                      finite_attempts=finite_attempts),
                  retry_proxy_q=q, service_interpretation='one complete attempt, all branch states verified' if attempts is None else 'exactly two attempts, second succeeds',
                  write_breakdown_ns=dict(front=front, one_attempt=one, write_slots=2*s['write_access_slot_ns'],
                      polarity_switch=td, verify_read=2*s['read_response_ns'], verify_compare=2*td,
                      retries=(finite_attempts-1)*one),
                  stream_breakdown_ns=dict(media=counts['read_rounds']*s['read_response_ns'],
                      digital=counts['digital_ticks']*td, boundary=CFG['boundary_ticks']*td),
                  dominant='stream: repeated bitcell-read/digital rounds; resident: two write-access slots',
                  sources=['MRAM-06 pp.2,4,5,9 / SI p.4','MRAM-03 pp.5-7','MRAM-04 pp.1-2','shared_baseline'],
                  assumptions=I['retry_model']['assumptions'])
    return result


def results():
    rows = [calculate(s) for s in I['scenarios']]
    ref = next(s for s in I['scenarios'] if s['profile']=='reference')
    comp = calculate(ref, I['comparison']['attempts'])
    comp['id'] = I['comparison']['id']
    mapping = dict(logical_capacity_Byte=api.L['resident_capacity_Byte'],
                   logical_weight_bits=8*api.L['resident_capacity_Byte'],
                   physical_MTJs=8*api.L['resident_capacity_Byte']*M['MTJs_per_weight_bit'],
                   groups_per_matrix=api.L['resident_capacity_Byte']//M['logical_weights_per_write_group'], **M)
    return dict(case_id=I['case_id'], baseline_id=api.D['baseline_id'], baseline_hashes=I['baseline_hashes'],
                units={'time':'ns','rho_tau':'Byte/s','ridge':'dimensionless'}, mode=I['mode'],
                mapping=mapping, scenarios=rows, comparison=comp,
                paired_ranges={k:[min(r[k] for r in rows),max(r[k] for r in rows)] for k in ['rho_Byte_per_s','tau_Byte_per_s','ridge']})


def generated():
    r = results()
    lines = [r'% Generated by check_mram.py --emit.', r'\begin{table}[htbp]\centering\small',
             r'\begin{tabular}{@{}lrrrrrr@{}}\toprule',
             r'情景 & $t_m/t_W$ (ns) & $\Delta_S$ (ns) & $\Delta_R$ (ns) & $\rho$ (GB/s) & $\tau$ (GB/s) & $\mathrm{RI}^{*}$\\\midrule']
    labels={'short':'短','reference':'参考','long':'长'}
    for s in r['scenarios']:
        lines.append(f"{labels[s['profile']]} & {s['read_response_ns']:g}/{s['write_access_slot_ns']:g} & {s['delta_S_ns']:g} & {s['delta_R_ns']:g} & {s['rho_Byte_per_s']/1e9:.5f} & {s['tau_Byte_per_s']/1e9:.5f} & {s['ridge']:.4f}\\\\")
    s=r['comparison']
    lines.extend([r'\midrule',f"参考，重写一次 & 5/30 & {s['delta_S_ns']:g} & {s['delta_R_ns']:g} & {s['rho_Byte_per_s']/1e9:.5f} & {s['tau_Byte_per_s']/1e9:.5f} & {s['ridge']:.4f}\\\\",
                  r'\bottomrule\end{tabular}',
                  r'\caption{成对情景：$B_S=128$ Byte，$B_R=8$ Byte。前三行为单轮完整写验通过的有限预算；末行为恰好一次整组重写且随后成功的占用对照，未纳入前三行情景范围。}',r'\end{table}'])
    return {'data/results.json':json.dumps(r,ensure_ascii=False,indent=2)+'\n','tex/generated_results.tex':'\n'.join(lines)+'\n'}


class Checks(unittest.TestCase):
    def test_shared_and_source_hashes(self):
        for path,h in I['baseline_hashes'].items():
            self.assertEqual(hashlib.sha256((SHARED/path).read_bytes()).hexdigest(),h)
        manifest={s['source_id']:s for s in json.loads((CORPUS/'source_manifest.json').read_text())['sources']}
        for key,s in I['sources'].items():
            self.assertEqual(s['pdf'],manifest[key]['pdf'])
            for p in [s['pdf']]+s['supplements']:
                self.assertEqual(hashlib.sha256((CORPUS/p['path']).read_bytes()).hexdigest(),p['sha256'])

    def test_mapping_resource_and_precision(self):
        n=api.dcim_counts(CFG)
        self.assertEqual(n['compute_rounds'],256)
        self.assertEqual(n['read_rounds'],256)
        self.assertEqual(M['active_compute_pairs'],CFG['rows_per_group']*CFG['output_lanes']*CFG['weight_bits_per_round'])
        self.assertEqual(M['encoded_load_bits'],M['logical_weights_per_write_group']*8*M['MTJs_per_weight_bit'])
        self.assertEqual(M['first_phase_active_MTJs'],M['selected_pairs_per_write_group']*2)
        self.assertEqual(M['second_phase_active_MTJs'],M['selected_pairs_per_write_group'])
        self.assertEqual(M['physical_direction_driver_lanes'],M['first_phase_active_MTJs'])
        self.assertEqual(M['verify_single_ended_sense_lanes']*M['verify_branch_batches'],M['encoded_load_bits'])
        self.assertEqual(results()['mapping']['physical_MTJs'],262144)
        # Explicitly enumerate full logical coverage, no duplicated resident payload.
        covered={(i,o) for i in range(api.L['n_in']) for start in range(0,api.L['n_out'],8) for o in range(start,start+8)}
        self.assertEqual(len(covered),16384)
        # Signed 128-term INT8 extremes fit the common 24-bit output container.
        self.assertLess(128*128*128,2**(api.L['output_container_bits']-1))

    def test_independent_arithmetic_and_aggregation(self):
        for s in results()['scenarios']:
            td=api.C['propagation']['profile_values'][s['profile']]['digital_tick']
            tm,tw=s['read_response_ns'],s['write_access_slot_ns']
            self.assertAlmostEqual(s['delta_S_ns'],256*(tm+td)+2*td)
            one=2*tw+2*tm+3*td
            self.assertAlmostEqual(s['delta_R_ns'],2*td+one)
            self.assertAlmostEqual(s['ridge'],16*s['delta_R_ns']/s['delta_S_ns'])
            self.assertAlmostEqual(s['tau_Byte_per_s'],16384/api.seconds(2048*s['delta_R_ns'],'ns'))
            self.assertEqual(s['resident_counts']['verified_MTJs_per_attempt'],128)
        ref=results()['scenarios'][1]
        self.assertEqual(ref['delta_S_ns'],2570)
        self.assertEqual(ref['write_breakdown_ns']['one_attempt'],85)
        self.assertEqual(ref['delta_R_ns'],95)
        self.assertEqual(results()['comparison']['delta_R_ns'],180)

    def test_generated_contract(self):
        for p,text in generated().items():
            self.assertEqual((BASE/p).read_text(),text)
        for word in ['互补','单端','192','自终止','条件','MRAM-01']:
            self.assertIn(word,(BASE/'tex/06_mram.tex').read_text())
        self.assertIn('generated_results',(BASE/'tex/06_mram.tex').read_text())


if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--emit',action='store_true')
    args=p.parse_args()
    if args.emit:
        for path,text in generated().items():
            (BASE/path).write_text(text)
    raise SystemExit(0 if unittest.TextTestRunner(verbosity=2).run(unittest.defaultTestLoader.loadTestsFromTestCase(Checks)).wasSuccessful() else 1)
