#!/usr/bin/env python3
"""Validate v0.1 payload, schedules, examples, sources and TeX tables (stdlib only).

--emit writes the two TeX tables from the JSON; default mode checks without edits.
"""
import argparse
import hashlib
import json
import math
from pathlib import Path
import unittest

BASE = Path(__file__).resolve().parents[1]
CORPUS = BASE.parents[1]
D = json.loads((BASE / 'data/shared_parameters.json').read_text())
P = D['periphery_parameters']


def seconds(value, unit):
    return value * {'s': 1, 'ms': 1e-3, 'us': 1e-6, 'ns': 1e-9}[unit]


def payload(elements, bits):
    return elements * bits / 8


def rate(byte_count, time_s):
    assert byte_count > 0 and time_s > 0
    return byte_count / time_s


def outward(value, lower, digits=2):
    scale = 10 ** (math.floor(math.log10(value)) - digits + 1)
    rounded = (math.floor(value / scale + 1e-10) if lower
               else math.ceil(value / scale - 1e-10)) * scale
    return float(f'{rounded:.10g}')


def interval(values):
    return f'{outward(min(values), True):g}--{outward(max(values), False):g}'


def step_counts():
    a, c, l = D['acim'], D['dcim'], D['logical_configuration']
    na = (math.ceil(l['b_S'] * 8 / a['input_bits_per_step'])
          * math.ceil(a['weight_planes'] / a['parallel_weight_planes'])
          * math.ceil(l['n_in'] / a['rows_per_step'])
          * math.ceil(l['n_out'] / a['adc_per_weight_plane']))
    nd = (math.ceil(l['b_S'] * 8 / c['input_bits_per_tick'])
          * math.ceil(l['n_in'] / c['rows_per_group'])
          * math.ceil(l['n_out'] / c['output_lanes']))
    return na, nd


def recompute(example, scenario):
    v = D['propagation']['profile_values'][scenario['profile']]
    td, x = v['digital_tick'], scenario['inputs']
    na, nd = step_counts()
    if example['id'].endswith('direct'):
        ds = na * (v['input_step'] + x['media_read_ns'] + v['adc_batch'] + 2 * td) + 2 * td
        dr = 2 * td + x['complete_physical_update_ns']
        br = x['physical_bits_completed'] / 8
    else:
        ds = nd * (x['media_read_ns'] + td) + 2 * td
        beats = math.ceil(x['mapped_page_bits'] / D['resident']['physical_write_data_lanes'])
        dr = (beats + 2) * td + 1000 * (x['page_program_full_us'] + x['erase_us'] / x['pages_per_erase'])
        br = x['mapped_page_bits'] / 8
    bs = payload(D['logical_configuration']['n_in'], 8)
    rho, tau = rate(bs, seconds(ds, 'ns')), rate(br, seconds(dr, 'ns'))
    return ds, dr, bs, br, rho, tau, rho / tau


def parameter_table():
    text = [r'% Generated by scripts/check_shared.py --emit; verify without --emit.',
            r'\begingroup\small',
            r'\begin{longtable}{@{}>{\raggedright\arraybackslash}p{23mm}>{\raggedright\arraybackslash}p{49mm}>{\raggedright\arraybackslash}p{24mm}>{\raggedright\arraybackslash}p{58mm}@{}}',
            r'\caption{核心外围参数与范围。范围为本文参考选择或其推导，来源 ID 为依据；每项按所列粒度使用。}\label{tab:periphery}\\',
            r'\toprule 模块 & 定义、服务粒度 & 范围/推荐 & 来源、选择与用途\\\midrule\endfirsthead',
            r'\toprule 模块 & 定义、服务粒度 & 范围/推荐 & 来源、选择与用途\\\midrule\endhead']
    definitions = {
        'input_step': '128 路二电平输入、缓冲与公共复位；每次物理求值步骤。',
        'adc_batch': '一颗 ADC 一个样本的采样、转换、局部锁存时隙；一批 128 颗并行。',
        'digital_tick': '一个公共数字阶段；ACIM 每批重构两拍，DCIM 每计算组一拍。',
        'write_control': '每个更新事务的准备和完成两拍；数据批、脉冲及读回按所含边界另计。'}
    uses = {
        'input_step': '本文选择；不含介质 RC、积分及专用电压建立。',
        'adc_batch': '本文选择；名义 10 bit、有效约 8 bit；10 ns 为采样周期锚点。',
        'digital_tick': '本文选择；带局部归约/寄存资源预算；参考 200 MHz。',
        'write_control': r'推导 $T_W=2T_D$；含此功能的完整更新周期替代该项。'}
    for key, p in P.items():
        refs = ', '.join(r'\sid{' + s + '}' for s in p['sources'])
        bounds = f"{p['range'][0]}--{p['range'][1]} ns"
        text.append(f"{p['label']} ${p['symbol']}$ & {definitions[key]} & {bounds}\\newline 推荐 {p['reference']} ns & {refs}。\\newline {uses[key]}\\\\")
    text += [r'\bottomrule\end{longtable}', r'\endgroup', '']
    return '\n'.join(text)


def example_table():
    text = [r'% Generated by scripts/check_shared.py --emit; illustrative, no medium binding.',
            r'\begin{table}[htbp]\centering\small',
            r'\begin{tabular}{@{}llrrrrr@{}}\toprule',
            r'示意 & 情景 & $\Delta_S$ (ns) & $\Delta_R$ (ns) & $\rho$ (GB/s) & $\tau$ (GB/s) & $\RI^*$\\\midrule']
    labels = {'short': '短时隙', 'reference': '参考', 'long': '长时隙'}
    for i, e in enumerate(D['examples'], 1):
        for s in e['scenarios']:
            text.append(f"{i} & {labels[s['profile']]} & {s['delta_S_ns']:g} & {s['delta_R_ns']:g} & {s['rho_Byte_per_s']/1e9:.4g} & {s['tau_Byte_per_s']/1e9:.4g} & {s['ridge']:.4g}\\\\")
        if i == 1:
            text.append(r'\midrule')
    text += [r'\bottomrule\end{tabular}',
             r'\caption{两个算例的成对情景。时间列保留算术结果用于复算，非器件测量精度；GB 为 $10^9$ Byte。}',
             r'\label{tab:examples}\end{table}']
    for i, e in enumerate(D['examples'], 1):
        ss = e['scenarios']
        rr, tt, ri = ([s[key] / (1e9 if key != 'ridge' else 1) for s in ss]
                      for key in ['rho_Byte_per_s', 'tau_Byte_per_s', 'ridge'])
        outer = [min(rr) / max(tt), max(rr) / min(tt)]
        text.append(f"示意 {i} 的展示范围为 $\\rho$={interval(rr)} GB/s、$\\tau$={interval(tt)} GB/s，成对 ridge 为 {interval(ri)}；独立端点外包络为 {interval(outer)}。")
    return '\n'.join(text) + '\n'


class SharedChecks(unittest.TestCase):
    def test_units_and_sampling(self):
        self.assertEqual(payload(128, 8), 128)
        self.assertEqual(payload(128, 4), 64)
        self.assertAlmostEqual(seconds(1000, 'ns'), seconds(1, 'us'))
        self.assertAlmostEqual(seconds(1000, 'us'), seconds(1, 'ms'))
        self.assertAlmostEqual(1 / (100 * 1e6), seconds(10, 'ns'))
        self.assertAlmostEqual(1e9 / (100 * 1e6), 10)
        self.assertAlmostEqual(1e9 / (455 * 1e6), 2.1978021978)

    def test_granularity_and_precision(self):
        a, l = D['acim'], D['logical_configuration']
        self.assertEqual(step_counts(), (64, 256))
        self.assertEqual(a['physical_steps_per_vector'], 64)
        self.assertEqual(D['dcim']['compute_steps_per_vector'], 256)
        self.assertEqual(a['adc_total'], a['adc_per_weight_plane'] * a['parallel_weight_planes'])
        self.assertEqual(a['adc_batches_per_vector'] * a['adc_total'], a['scalar_conversions_per_vector'])
        self.assertEqual(a['scalar_conversions_per_vector'], l['n_out'] * 8 * 8)
        self.assertEqual(l['B_S_Byte'], l['n_in'] * l['b_S'])
        self.assertEqual(l['resident_capacity_Byte'], l['n_in'] * l['n_out'] * l['b_R'])
        self.assertGreaterEqual(2 ** a['partial_sum_code_bits'], a['partial_sum_max'] + 1)
        self.assertLess(128 * 128 * 128, 2 ** (l['output_container_bits'] - 1))

    def test_dimension_and_ridge_grain(self):
        bs, br, ds, dr = 128, 16, 3850e-9, 60e-9
        rho, tau = rate(bs, ds), rate(br, dr)
        self.assertAlmostEqual(rho / tau, (bs / br) * (dr / ds))
        self.assertAlmostEqual((rho / tau) / (dr / ds), 8)
        self.assertAlmostEqual(rate(1, seconds(1, 'ns')) / 1e9, 1)

    def test_monotonicity_and_replication(self):
        for e in D['examples']:
            for s in e['scenarios']:
                r, t = s['rho_Byte_per_s'], s['tau_Byte_per_s']
                self.assertLess(rate(s['B_S_Byte'], seconds(2 * s['delta_S_ns'], 'ns')), r)
                self.assertLess(rate(s['B_R_Byte'], seconds(2 * s['delta_R_ns'], 'ns')), t)
                self.assertAlmostEqual((7 * r) / (7 * t), s['ridge'])
                self.assertAlmostEqual(rate(1024 * s['B_R_Byte'], seconds(1024 * s['delta_R_ns'], 'ns')), t)

    def test_page_erase_and_verify(self):
        # One full block: 16 page programs + one erase, equivalent to per-page amortization.
        self.assertAlmostEqual(256 * 16 / seconds(16 * 10 + 200, 'us'),
                               256 / seconds(10 + 200 / 16, 'us'))
        self.assertEqual(math.ceil(2048 / 128), 16)
        # Same logical update, four pulse/verify pairs; payload unchanged.
        br, pulse, verify, k = 16, 20, 10, 4
        full = k * (pulse + verify)
        self.assertEqual(full, 120)
        self.assertEqual(rate(br, seconds(full, 'ns')), rate(br, seconds(120, 'ns')))
        self.assertLess(rate(br, seconds(full, 'ns')), rate(br, seconds(pulse + verify, 'ns')))
        self.assertEqual(D['resident']['default_binary_unredundant_completed_Byte_per_parallel_batch'], 128 / 8)

    def test_profiles_and_periphery(self):
        self.assertEqual(D['baseline_version'], 'v0.1')
        for v in D['propagation']['profile_values'].values():
            for key, val in v.items():
                self.assertLessEqual(P[key]['range'][0], val)
                self.assertLessEqual(val, P[key]['range'][1])
        self.assertEqual(P['write_control']['range'], [2*x for x in P['digital_tick']['range']])
        for p in P.values():
            self.assertIn(p['kind'], ['reference_choice', 'derived', 'reported'])
            self.assertTrue(set(p['sources']) <= set(D['sources']))
        self.assertEqual([64*(v['input_step']+v['adc_batch']+2*v['digital_tick'])+2*v['digital_tick']
                          for v in D['propagation']['profile_values'].values()], [1028, 2250, 5140])

    def test_saved_pairs_and_rounding(self):
        self.assertEqual(len(D['examples']), 2)
        for e in D['examples']:
            self.assertFalse(e['bound_to_medium'])
            for s in e['scenarios']:
                actual = recompute(e, s)
                for key, val in zip(['delta_S_ns','delta_R_ns','B_S_Byte','B_R_Byte',
                                     'rho_Byte_per_s','tau_Byte_per_s','ridge'], actual):
                    self.assertTrue(math.isclose(s[key], val, rel_tol=1e-12), (e['id'], key))
                    self.assertLessEqual(outward(val, True), val + 1e-10)
                    self.assertGreaterEqual(outward(val, False) + 1e-10, val)
        self.assertEqual(D['examples'][0]['scenarios'][1]['delta_S_ns'], 3850)
        self.assertEqual(D['examples'][1]['scenarios'][1]['delta_R_ns'], 22590)

    def test_sources_and_tex_tables(self):
        manifest = {s['source_id']: s for s in json.loads((CORPUS/'source_manifest.json').read_text())['sources']}
        bib = (BASE/'tex/references.bib').read_text()
        evidence = (BASE/'notes/evidence.zh.md').read_text()
        for key, source in D['sources'].items():
            self.assertEqual(source['pdf'], manifest[key]['pdf'])
            self.assertEqual(hashlib.sha256((CORPUS/source['pdf']['path']).read_bytes()).hexdigest(), source['pdf']['sha256'])
            self.assertTrue(('@article{' + key + ',' in bib) or ('@inproceedings{' + key + ',' in bib))
            self.assertIn(key, evidence)
        self.assertEqual((BASE/'tex/generated_parameters.tex').read_text(), parameter_table())
        self.assertEqual((BASE/'tex/generated_examples.tex').read_text(), example_table())
        one = (BASE/'tex/01_cmos_periphery.tex').read_text()
        two = (BASE/'tex/02_estimation_method.tex').read_text()
        self.assertIn(r'\input{generated_parameters}', one)
        self.assertIn(r'\input{generated_examples}', two)
        self.assertEqual((one + two).count(r'\section{'), 2)
        self.assertIn('1028、2250、5140', one)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--emit', action='store_true')
    args = parser.parse_args()
    if args.emit:
        (BASE/'tex/generated_parameters.tex').write_text(parameter_table())
        (BASE/'tex/generated_examples.tex').write_text(example_table())
    result = unittest.TextTestRunner(verbosity=2).run(unittest.defaultTestLoader.loadTestsFromTestCase(SharedChecks))
    raise SystemExit(0 if result.wasSuccessful() else 1)
